<a href="https://colab.research.google.com/github/shubhangi-singh21/Data-Science/blob/master/For_Loop%2C_Array_and_Dictionary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# For Loop

A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc

In [ ]:
for i in range(0, 6, 2):
    print(i)


0
2
4


In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


Even strings are iterable objects, they contain a sequence of characters:

In [ ]:
for x in "banana":
  print(x)

b
a
n
a
n
a


Resource : https://www.w3schools.com/python/python_for_loops.asp

# Array

An array is a special variable, which can hold more than one value at a time.

In [ ]:
from numpy import array

In [ ]:
num = array([1, 2, 3])

In [ ]:
num

array([1, 2, 3])

An array can hold many values under a single name, and you can access the values by referring to an index number.

In [ ]:
print(num[0])

1


So how are arrays different from lists?

In [ ]:
print(num/3)

[0.33333333 0.66666667 1.        ]


In [ ]:
num_list = [1, 2, 3]
print(num_list)
print(num_list/3)

[1, 2, 3]


TypeError: ignored

In [ ]:
for i in range(len(num_list)):
  num_list[i] = num_list[i]/3

In [ ]:
num_list

[0.3333333333333333, 0.6666666666666666, 1.0]

In [ ]:
n_arr = array([1, 2, 3])
n_list = [1, 2, 3]

In [ ]:
n_arr/3

array([0.33333333, 0.66666667, 1.        ])

In [ ]:
n_arr

array([1, 2, 3])

In [ ]:
n_list/3

TypeError: ignored

In [ ]:
for i in range(len(n_list)):
  n_list[i] = n_list[i]/3

print(n_list)

[0.3333333333333333, 0.6666666666666666, 1.0]


Arrays can handle mathematical operations but lists cannot.

Resource : https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

https://medium.com/backticks-tildes/list-vs-array-python-data-type-40ac4f294551

# Dictionary

Dictionary in Python is an unordered collection of data values, used to store data values like a map, which unlike other Data Types that hold only single value as an element, Dictionary holds key:value pair. Key value is provided in the dictionary to make it more optimized. Each key-value pair in a Dictionary is separated by a colon :, whereas each key is separated by a ‘comma’.

A Dictionary in Python works similar to the Dictionary in a real world. Keys of a Dictionary must be unique and of immutable data type such as Strings, Integers and tuples, but the key-values can be repeated and be of any type.

In [ ]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "max speed": 45.65
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'max speed': 45.65}


You can access the items of a dictionary by referring to its key name, inside square brackets:

In [ ]:
x = thisdict["brand"]
print(x)

Ford


You can change the value of a specific item by referring to its key name:

In [ ]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print(thisdict)

thisdict["year"] = 2018

print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}


In [ ]:
d = {"St 1":{ "M1":45, "M2":45, "M3":45},
     "St 2":{ "M1":45, "M2":45, "M3":45},
     "St 3":{ "M1":45, "M2":45, "M3":45}  
}}

You cannot copy a dictionary simply by typing dict2 = dict1, because: dict2 will only be a reference to dict1, and changes made in dict1 will automatically also be made in dict2.

There are ways to make a copy, one way is to use the built-in Dictionary method copy().

In [ ]:
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}


You can get all the keys or all the values of a dictionary using the methods keys() and values().

In [ ]:
print(mydict.keys())
print(mydict.values())

dict_keys(['brand', 'model', 'year'])
dict_values(['Ford', 'Mustang', 2018])


You can loop through a dictionary by using a for loop.

When looping through a dictionary, the return value are the keys of the dictionary, but there are methods to return the values as well.

In [ ]:
# Print all key names in the dictionary, one by one:

for x in thisdict:
  print(x) 

brand
model
year


In [ ]:
# Print all values in the dictionary, one by one:

for x in thisdict:
  print(thisdict[x]) 

Ford
Mustang
2018


In [ ]:
# Loop through both keys and values, by using the items() function:

for x, y in thisdict.items():
  print(x, y) 

brand Ford
model Mustang
year 2018


In [ ]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}

In [ ]:
thisdict["speed"] = 67

In [ ]:
thisdict.update({"speed":67})

In [ ]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'speed': 67, 'year': 2018}

Resource : https://www.w3schools.com/python/python_dictionaries.asp